import { ThemeProvider } from "@/components/theme-provider";
import SettingsProvider from "@/utils/settings/provider";
import { getSettings } from "@/utils/settings/server";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400"],
	display: "swap",
});
export const metadata: Metadata = {
	title: "Kanban",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const initialSettings = await getSettings();
	return (
		<html lang="en" suppressHydrationWarning className={`${poppins.variable}`}>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<SettingsProvider initial={initialSettings}>
						<main className="h-full">{children}</main>
					</SettingsProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
