import type { BoardT, ColumnT, CardT } from "@/components/kanban/types";

export const DEMO_BOARD_ID = "demo-board-1";
export const DEMO_USER_ID = "demo-user";

// Initial demo cards
const demoCards: CardT[] = [
	{
		__typename: "Card",
		id: "demo-card-1",
		columnId: "demo-column-1",
		boardId: DEMO_BOARD_ID,
		title: "Welcome to the Demo!",
		description: "Try dragging this card to another column. You can also edit or delete cards.",
		order: 0,
		assignedTo: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		dueDate: null,
		completed: false,
		tags: ["welcome", "demo"],
	},
	{
		__typename: "Card",
		id: "demo-card-2",
		columnId: "demo-column-1",
		boardId: DEMO_BOARD_ID,
		title: "Create new cards",
		description: "Click the '+' button in any column to create a new card",
		order: 1,
		assignedTo: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		dueDate: null,
		completed: false,
		tags: ["tutorial"],
	},
	{
		__typename: "Card",
		id: "demo-card-3",
		columnId: "demo-column-2",
		boardId: DEMO_BOARD_ID,
		title: "Design mockups",
		description: "Create high-fidelity mockups for the new feature",
		order: 0,
		assignedTo: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		dueDate: null,
		completed: false,
		tags: ["design"],
	},
	{
		__typename: "Card",
		id: "demo-card-4",
		columnId: "demo-column-3",
		boardId: DEMO_BOARD_ID,
		title: "Review pull request",
		description: "Code review for the authentication feature",
		order: 0,
		assignedTo: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		dueDate: null,
		completed: false,
		tags: ["review"],
	},
	{
		__typename: "Card",
		id: "demo-card-5",
		columnId: "demo-column-4",
		boardId: DEMO_BOARD_ID,
		title: "Launch blog post",
		description: "Published announcement about the new release",
		order: 0,
		assignedTo: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		dueDate: null,
		completed: true,
		tags: ["marketing", "done"],
	},
];

// Initial demo columns
const demoColumns: ColumnT[] = [
	{
		__typename: "Column",
		id: "demo-column-1",
		boardId: DEMO_BOARD_ID,
		title: "To Do",
		order: 0,
		description: "Tasks that need to be started",
		startDate: null,
		endDate: null,
		status: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		cards: demoCards.filter((card) => card.columnId === "demo-column-1"),
	},
	{
		__typename: "Column",
		id: "demo-column-2",
		boardId: DEMO_BOARD_ID,
		title: "In Progress",
		order: 1,
		description: "Tasks currently being worked on",
		startDate: null,
		endDate: null,
		status: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		cards: demoCards.filter((card) => card.columnId === "demo-column-2"),
	},
	{
		__typename: "Column",
		id: "demo-column-3",
		boardId: DEMO_BOARD_ID,
		title: "Review",
		order: 2,
		description: "Tasks awaiting review or approval",
		startDate: null,
		endDate: null,
		status: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		cards: demoCards.filter((card) => card.columnId === "demo-column-3"),
	},
	{
		__typename: "Column",
		id: "demo-column-4",
		boardId: DEMO_BOARD_ID,
		title: "Done",
		order: 3,
		description: "Completed tasks",
		startDate: null,
		endDate: null,
		status: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		cards: demoCards.filter((card) => card.columnId === "demo-column-4"),
	},
];

// Initial demo board
export const initialDemoBoard: BoardT = {
	__typename: "Board",
	id: DEMO_BOARD_ID,
	title: "Demo Project Board",
	ownerId: DEMO_USER_ID,
	members: [DEMO_USER_ID],
	createdAt: new Date().toISOString(),
	updatedAt: new Date().toISOString(),
	description: "Try out all the kanban features in this demo board!",
	color: "#3b82f6",
	isFavorite: false,
	isArchived: false,
	tags: ["demo", "sample"],
	columns: demoColumns,
};
